name: deploy to github pages

on:
  push:
    tags: [v*]

jobs:
  deploy:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: |
          source ./export_env.sh
          npm ci
          npm test
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
